### ISSUE TITLE
Document how to specify OS image

### ISSUE THREAD

**Issue by sungwonh** [kubevirt/demo#10]
Could you please add a guide on how to specify OS image (e.g., Fedora or Ubuntu) and where to locate the OS image file (e.g., .img file) on a host when create a VM?

**Comment by warmchang** [comment]
Check the Makefile, when you run "make build", it will use the virt-builder centos-7.3 to compile kubevirt-demo.img.

> build: data/bootstrap-kubevirt.sh Makefile
> 	virt-builder centos-7.3 \
> 		--no-network \
> 		--smp 4 --memsize 2048 \
> 		--output $(IMAGE) \
> 		--format qcow2 \
> 		--size 20G \
> 		--hostname kubevirt-demo \
> 		--upload data/bootstrap-kubevirt.sh:/ \
> 		--root-password password: \
>                 --run-command "echo -e Login as \'root\' to proceed.\\\\n >> /etc/issue" \
> 		--firstboot-command "GIT_TAG=$(GIT_TAG) bash -x /bootstrap-kubevirt.sh ; init 0 ;"
> 	@echo "Deploying KubeVirt inside the VM - This can take a while (progress: tail -f build.log)"
> 	@./run-demo.sh $(IMAGE) 2>&1 > build.log
> 	@echo "KubeVirt got deployed successful."
> 	@echo "Now run: ./run-demo.sh"

**Comment by sungwonh** [comment]
I mean a VM created by virt-handler when run the command "kubectl create -f vm.json". Could you tell me how to specify OS image in the vm.json file and where to locate that OS image file on a host?

**Comment by warmchang** [comment]
No idear about this. Actually, I have not try this repo successfully because of  https://github.com/kubevirt/demo/issues/9

**Comment by fabiand** [comment]
@warmchang the run-demo.sh is just starting the vm which contains the kubevirt setup - it's actually not releated how kubevirt is starting vms.

**Comment by fabiand** [comment]
@sungwonh So - vm.json maps pretty much to the libvirt domainxml. You can try to use an iscsi or rbd volume and attach it as a root volume to the vm.

**Comment by sungwonh** [comment]
@fabiand Thanks. I'll try.

**Comment by fabiand** [comment]
Fixed by #14
