### ISSUE TITLE
[doc] Broken link to documentation

### ISSUE THREAD

**Issue by anthonydahanne** [kubevirt/demo#128]
In the main `readme` there's a  link named `user guide` that links to `http://docs.kubevirt.io/`.

Unfortunately, this page seems to be a parking page for a german hoster, selfhost.de
Also, it'd be nice if the link was https; I actually tried `https://docs.kubevirt.io/` , but I got nothing at all.

**Comment by codificat** [comment]
Many thanks for reporting!

The `docs` CNAME might have broken with the move of the domain to the CNCF - we'll investigate that separatedly, but in any case the user guide is in a [different location](https://kubevirt.io/user-guide/docs/latest/welcome/index.html).

**Comment by anthonydahanne** [comment]
cool, that is fixed indeed, thanks!
