### ISSUE TITLE
Adding file of 'CONTRIBUTING.md' and LICENSE for the project

### ISSUE THREAD

**Issue by lubinszARM** [kubevirt/demo#135]
Hi,
We want to add some ARM64 related descriptions, but there is no 'CONTRIBUTING.md' and LICENSE here, so we are not able to contribute code here. Can you add the files?
Example：
https://github.com/hustcat/sriov-cni/blob/master/LICENSE
https://github.com/hustcat/sriov-cni/blob/master/CONTRIBUTING.md
Guideline:
https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors
https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by lubinszARM** [comment]
cc @kalyxin02

**Comment by lubinszARM** [comment]
@fabiand @iranzo 
Any comments?
Thanks.

**Comment by fabiand** [comment]
@lubinszARM Heya! Good idea.

DO you mind opening a PR which is adding those files?

**Comment by fabiand** [comment]
And: How far did you get to get KubeVirt running on ARM?

**Comment by lubinszARM** [comment]
Hi @fabiand 
We can already use kubeadm to deploy kubevirt on Arm64 internally.
Also, we are trying to dliver the PR-s to upstream.
Such as: https://github.com/kubevirt/kubevirt/pull/3415

**Comment by lubinszARM** [comment]
> @lubinszARM Heya! Good idea.
> 
> DO you mind opening a PR which is adding those files?

Our legal department needs to review these two documents, otherwise we cannot submit PR-s.

**Comment by fabiand** [comment]
Oh, ok, then let me help you to submit some defaults.

**Comment by fabiand** [comment]
> We can already use kubeadm to deploy kubevirt on Arm64 internally.
> Also, we are trying to push the PR-s to upstream.

Pretty awesome!

If we want to enable this for kubevirt in releases, then we also need CI (maybe you have some hardware we could use for CI?) - and we also want to add it to the travis ci of this demo. If travis is uspporting arm ..

**Comment by fabiand** [comment]
Done.
