### ISSUE TITLE
[FAILED] Failed to start Docker Storage Setup.

### ISSUE THREAD

**Issue by rmohr** [kubevirt/demo#2]
After the intial setup I always see

```
[FAILED] Failed to start Docker Storage Setup.
```

in the boot log. However it does not seem to be critical since everything seems to work fine.

**Comment by fabiand** [comment]
Yes. An annoying problem. I wonder why they don't fix it in the docker storag esteup.

**Comment by fabiand** [comment]
Fixed by #14
