### ISSUE TITLE
Issue with current minikube 1.8 and run-demo

### ISSUE THREAD

**Issue by jberkus** [kubevirt/demo#23]
Currently, to install kubernetes 1.8 on minikube you have to use the bootstrap=kubeadm option.

Due to a bug, this causes the minikube status output to be messed up:

```
[root@redhat demo]# minikube status
minikube: Running
cluster: Stopped
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.42.191
```

This causes run-demo to refuse to start because "minikube is installed but not running".

If you comment out the check for minikube running, the demo works fine.

**Comment by fabiand** [comment]
Fixed with a previous change.
