### ISSUE TITLE
Add automation

### ISSUE THREAD

**Issue by fabiand** [kubevirt/demo#27]
We should add automation in order to ensure that the demo continues to work with releases of KubeVirt.

**Comment by fabiand** [comment]
@gbenhaim you added automation for kubevirt-ansible.

Do you think oVirt CI will allow us to run minikube as well? It's using libvirt so I'm optimistic

/cc @ifireball

**Comment by ifireball** [comment]
@fabiand we could probably make it work

**Comment by fabiand** [comment]
Fixed!
