### ISSUE TITLE
Update demo to  as per kubevirt v0.2.0

### ISSUE THREAD

**Issue by surajnarwade** [kubevirt/demo#31]
Since, `virt-api` service is removed in `v0.2.0`, I think demo information should also changed to latest one.

**Comment by fabiand** [comment]
Yes, there is #30 - but there were some issues with virtctl, this is why I didn't update it yet.

Maybe the better strategy is to update, and note that virtctl is broken, and then quickly update to 0.3 where this should be fixed.
