### ISSUE TITLE
Error from server: Invalid JSON Patch

### ISSUE THREAD

**Issue by drpaneas** [kubevirt/demo#38]
After running:

`$ kubectl patch offlinevirtualmachine testvm --type merge -p '{"spec":{"running":true}}'
`

I get the $SUBJECT error.

```
C:\minikube> kubectl get --all-namespaces pods
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
kube-system   kube-addon-manager-minikube             1/1       Running   0          24m
kube-system   kube-dns-54cccfbdf8-grdkr               3/3       Running   0          24m
kube-system   kubernetes-dashboard-77d8b98585-66pxb   1/1       Running   0          24m
kube-system   storage-provisioner                     1/1       Running   0          24m
kube-system   virt-controller-5c74754ddd-5p4cx        1/1       Running   0          15m
kube-system   virt-controller-5c74754ddd-tbhkf        0/1       Running   0          15m
kube-system   virt-handler-c887w                      1/1       Running   0          15m
```

Shouldn't also the `virt-controller-5c74754ddd-tbhkf ` running? I am following [this](https://github.com/kubevirt/demo) guide

**Comment by drpaneas** [comment]
`kubectl get ovm testvm`

```bash
C:\minikube>kubectl get ovm testvm
NAME      AGE
testvm    1d
```

Nothing fancy here :/

**Comment by fabiand** [comment]
Argh - `kubectl get ovm testvm -o yaml` I mean to say - to get all the details.

**Comment by fabiand** [comment]
You are testing on Windows!? Crazy :)

**Comment by drpaneas** [comment]
Shit! I know why it's failing... or at least this my lucky guess:

virtual-box is unable of running KVM inside of it. It's not supported. Minikube in windows is using Virtual-box, so ... I will try this on my Linux box also to make sure if it's a bug or not, and then update the status here.

**Comment by fabiand** [comment]
Cool.

Are you sure it is not supported by today? KVM inside VB? ...

**Comment by drpaneas** [comment]
Yes. Check this: https://www.virtualbox.org/ticket/4032
9 years ...

**Comment by fabiand** [comment]
Oh - But never the less - We noticed that currently all VMs are run in emualtion mode. So this should not be the issue.

**Comment by drpaneas** [comment]
In Linux it works perfectly OK. So, the issue is triggered only in Windows environment.

**Comment by fabiand** [comment]
Can you provide the output of `kubectl get ovm testvm -o yaml` ?

**Comment by fabiand** [comment]
ping?

**Comment by drpaneas** [comment]
Ah I forgot about this. Let me resurrect my Windows machine. I will report soon-ish. Thank for the reminder ;)

**Comment by drpaneas** [comment]
```yaml
apiVersion: kubevirt.io/v1alpha1
kind: OfflineVirtualMachine
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubevirt.io/v1alpha1","kind":"OfflineVirtualMachine","metadata":{"annotations":{},"name":"testvm","namespace":"default"},"spec":{"running":false,"selector":{"matchLabels":{"guest":"testvm"}},"template":{"metadata":{"labels":{"guest":"testvm","kubevirt.io/size":"small"}},"spec":{"domain":{"devices":{"disks":[{"disk":{"bus":"virtio"},"name":"registrydisk","volumeName":"registryvolume"},{"disk":{"bus":"virtio"},"name":"cloudinitdisk","volumeName":"cloudinitvolume"}]}},"volumes":[{"name":"registryvolume","registryDisk":{"image":"kubevirt/cirros-registry-disk-demo"}},{"cloudInitNoCloud":{"userDataBase64":"SGkuXG4="},"name":"cloudinitvolume"}]}}}}
  clusterName: ""
  creationTimestamp: 2018-03-11T01:18:34Z
  generation: 0
  name: testvm
  namespace: default
  resourceVersion: "3371"
  selfLink: /apis/kubevirt.io/v1alpha1/namespaces/default/offlinevirtualmachines/testvm
  uid: 1e7a9b22-24ca-11e8-be68-080027a81666
spec:
  running: false
  selector:
    matchLabels:
      guest: testvm
  template:
    metadata:
      labels:
        guest: testvm
        kubevirt.io/size: small
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: registrydisk
            volumeName: registryvolume
          - disk:
              bus: virtio
            name: cloudinitdisk
            volumeName: cloudinitvolume
      volumes:
      - name: registryvolume
        registryDisk:
          image: kubevirt/cirros-registry-disk-demo
      - cloudInitNoCloud:
          userDataBase64: SGkuXG4=
        name: cloudinitvolume
```

Here it is.

**Comment by fabiand** [comment]
Closing this issue as the entities were renamed.

**Comment by fabiand** [comment]
Please reopen or file new if you still see this. Please provide:

Exact kubectl/oc cmdline
Exact VM/VMI definitnion.

**Comment by fromanirh** [comment]
Hey, I stumbled on this issue today. Seems a kubernetes issue: 
https://github.com/kubernetes/kubernetes/issues/63247
(also relevant: https://github.com/kubernetes/kubernetes/issues/56980)

I workarounded this issue using a YAML patch. No luck with JSON patch
platform: kubevirt 0.8.0 on kubernetes 1.11

**Comment by stealthybox** [comment]
@fromanirh there shouldn't be any issues parsing valid JSON, as it is a subset of YAML.
You likely had an error in your JSON which was not present in your YAML version of the patch.

The linked issues are mainly about UX of the jsonpatch feature. (it's confusing)
The parsing works correctly.

**Comment by woodwardmatt** [comment]
I'm sharing this having gone through the same battle yesterday with the kubectl run command. If you're running this on Windows using Powershell you'll need to create a system variable and assign the JSON (using the ConvertTo-Json routine) first. Then use that variable in your kubectl commands.

From the OP's code: 

`$ kubectl patch offlinevirtualmachine testvm --type merge -p '{"spec":{"running":true}}'`

Becomes:

```
$myjson = '{"spec":{"running":true}}'
$ kubectl patch offlinevirtualmachine testvm --type merge -p $myjson
```

Hope that helps! :)

**Comment by fabiand** [comment]
That's crazy ...

@woodwardmatt do I understand that you ran minikube on Windows and KubeVirt inside of minikube?
