### ISSUE TITLE
[FAILED] make build on Fedora 25

### ISSUE THREAD

**Issue by warmchang** [kubevirt/demo#9]
The env:

> [root@localhost demo]# cat /etc/redhat-release
> Fedora release 25 (Twenty Five)
> [root@localhost demo]# dnf install -y make qemu-system-x86 libguestfs-tools-c expect
> Last metadata expiration check: 16:15:44 ago on Mon Feb 13 00:31:53 2017.
> Package make-1:4.1-5.fc24.x86_64 is already installed, skipping.
> Package qemu-system-x86-2:2.7.1-2.fc25.x86_64 is already installed, skipping.
> Package libguestfs-tools-c-1:1.34.4-2.fc25.x86_64 is already installed, skipping.
> Package expect-5.45-22.fc24.x86_64 is already installed, skipping.
> Dependencies resolved.
> Nothing to do.
> Complete!
> 

Run make build, got the virt-resize error, any advice to solve it? thanks!

> [root@localhost demo]# make build
> virt-builder centos-7.3 \
>         --no-network \
>         --smp 4 --memsize 2048 \
>         --output kubevirt-demo.img \
>         --format qcow2 \
>         --size 20G \
>         --hostname kubevirt-demo \
>         --upload data/bootstrap-kubevirt.sh:/ \
>         --root-password password: \
>                 --run-command "echo -e Login as \'root\' to proceed.\\\\n >> /etc/issue" \
>         --firstboot-command "GIT_TAG=v0.0.1-alpha.2 bash -x /bootstrap-kubevirt.sh ; init 0 ;"
> [  33.8] Downloading: http://libguestfs.org/download/builder/centos-7.3.xz
> [  35.3] Planning how to build this image
> [  35.3] Uncompressing
> [  57.7] Resizing (using virt-resize) to expand the disk to 20.0G
> virt-resize: error: libguestfs error: could not create appliance through
> libvirt.
> 
> Try running qemu directly without libvirt using this environment variable:
> export LIBGUESTFS_BACKEND=direct
> 
> Original error from libvirt: Cannot access storage file
> '/root/demo/kubevirt-demo.img' (as uid:107, gid:107): Permission denied
> [code=38 int1=13]
> 
> If reporting bugs, run virt-resize with debugging enabled and include the
> complete output:
> 
>   virt-resize -v -x [...]
> Makefile:9: recipe for target 'build' failed
> make: *** [build] Error 1
> [root@localhost demo]#

**Comment by fabiand** [comment]
Fixed by #14
