### ISSUE TITLE
Deploy a VirtualMachine fails with The  "" is invalid: : spec.template.spec.volumes.containerDisk in body is a forbidden property

### ISSUE THREAD

**Issue by haidernitc** [kubevirt/demo#98]
We are using demo vm.yaml but it fails with below error. Kubervirt seems up and working.

[centos@ip-172-31-43-99 ~]$ kubectl apply -f https://raw.githubusercontent.com/kubevirt/demo/master/manifests/vm.yaml
The  "" is invalid: : spec.template.spec.volumes.containerDisk in body is a forbidden property

[centos@ip-172-31-43-99 kubevirt-ansible]$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                                                    READY   STATUS    RESTARTS   AGE
kube-system   coredns-86c58d9df4-5gpqn                                                1/1     Running   0          25m
kube-system   coredns-86c58d9df4-j7sqz                                                1/1     Running   0          25m
kube-system   etcd-ip-172-31-43-99.eu-central-1.compute.internal                      1/1     Running   0          24m
kube-system   kube-apiserver-ip-172-31-43-99.eu-central-1.compute.internal            1/1     Running   0          23m
kube-system   kube-cni-plugins-amd64-hv2zc                                            1/1     Running   0          24m
kube-system   kube-controller-manager-ip-172-31-43-99.eu-central-1.compute.internal   1/1     Running   0          24m
kube-system   kube-multus-amd64-2ztrz                                                 1/1     Running   0          24m
kube-system   kube-ovs-cni-plugin-amd64-pqdvw                                         1/1     Running   0          23m
kube-system   kube-proxy-mggdz                                                        1/1     Running   0          25m
kube-system   kube-scheduler-ip-172-31-43-99.eu-central-1.compute.internal            1/1     Running   0          24m
kube-system   virt-api-66d49464-7bg9s                                                 1/1     Running   0          23m
kube-system   virt-api-66d49464-c9x5z                                                 1/1     Running   0          23m
kube-system   virt-controller-7fb89fd44c-j2mlc                                        1/1     Running   0          23m
kube-system   virt-controller-7fb89fd44c-xnhqm                                        1/1     Running   0          23m
kube-system   virt-handler-k6bb4                                                      1/1     Running   0          23m
kube-system   weave-net-tdxwp                                                         2/2     Running   0          25m

**Comment by slintes** [comment]
@haidernitc Hi, `containerDisk` was renamed recently from `registryDisk`. What KubeVirt version are you running (`virtctl version`)? If it's not the latest, you either upgrade KubeVirt, or downgrade the VM spec by renaming `containerDisk` back to `registryDisk`.
